import { ArrowLeft } from 'lucide-react';

const LAST_UPDATED = '30 August 2026';

interface Props {
  onNavigate?: (route: string) => void;
}

export default function AcceptableUsePage({ onNavigate }: Props) {
  const handleNav = (route: string, e?: React.MouseEvent) => {
    if (e) e.preventDefault();
    if (onNavigate) onNavigate(route);
    else window.location.href = route;
  };

  return (
    <div className="min-h-screen bg-[#F5F5F2] text-[#1C1F1D] flex flex-col font-sans">

      <nav className="border-b border-[#D9DCD8] bg-white sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={(e) => handleNav('/', e)} className="flex items-center gap-2.5 cursor-pointer">
            <div className="w-8 h-8 rounded bg-[#556B5D] text-white flex items-center justify-center text-xs font-bold">
              NX
            </div>
            <span className="font-bold text-base text-[#1C1F1D]">
              NEXUS-CRIME
            </span>
          </button>
          <button onClick={(e) => handleNav('/', e)} className="inline-flex items-center gap-1.5 text-xs text-[#666B67] hover:text-[#1C1F1D] transition-colors cursor-pointer">
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to Workspace
          </button>
        </div>
      </nav>

      <main className="flex-1 max-w-4xl mx-auto px-6 py-12">
        <div className="space-y-1 mb-8 pb-4 border-b border-[#D9DCD8]">
          <h1 className="text-2xl font-bold text-[#1C1F1D] tracking-tight">Acceptable Use Policy</h1>
          <p className="text-xs text-[#666B67]">Last updated: {LAST_UPDATED}</p>
        </div>

        <article className="space-y-8 text-xs text-[#666B67] leading-relaxed">

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-[#1C1F1D]">1. Purpose</h2>
            <p>
              This Acceptable Use Policy ("AUP") defines the boundaries of permitted use for the NEXUS-CRIME 
              AI-Powered Criminal Network Analysis System. It supplements the Terms & Conditions and Privacy 
              Policy by providing specific, actionable guidelines for day-to-day use by investigators, 
              supervisors, and administrative personnel. Compliance with this AUP is mandatory. Violations 
              are subject to access revocation, departmental disciplinary proceedings, and potential 
              criminal prosecution.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">2. Permitted Use</h2>
            <p>The System may be used exclusively for:</p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Ingesting and correlating telecommunications, financial, and narrative data for active, warranted criminal investigations</li>
              <li>Reviewing and acting upon investigative leads generated by the System's correlation engine</li>
              <li>Exporting judicial dossiers and evidence chains for use in court filings and prosecutorial review</li>
              <li>Conducting quality assurance reviews of entity resolution decisions in the human-in-the-loop review queue</li>
              <li>Adjusting risk formula weights for calibration and sensitivity analysis, with all changes logged</li>
              <li>Reviewing the audit trail for compliance verification and internal oversight</li>
              <li>Generating de-identified statistical reports for departmental performance metrics (e.g., total cases processed, average correlation time), subject to supervisor approval</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">3. Prohibited Conduct</h2>
            <p>The following activities are strictly prohibited:</p>

            <h3 className="text-sm font-semibold text-slate-200">3.1 Unauthorized Investigations</h3>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Querying data about individuals, phone numbers, or locations not covered by the active warrant</li>
              <li>Running correlation jobs on personal acquaintances, family members, journalists, political figures, or any person for non-investigative purposes</li>
              <li>Using the System to conduct surveillance or monitoring that is not specifically authorized by the relevant warrant</li>
            </ul>

            <h3 className="text-sm font-semibold text-slate-200">3.2 Discriminatory Profiling</h3>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Using external knowledge of a subject's religion, caste, ethnicity, gender, political views, or sexual orientation to influence query formulation, entity resolution decisions, or risk weight adjustments</li>
              <li>Annotating, tagging, or labeling entities within the System with demographic attributes that the System does not natively collect</li>
              <li>Applying different scrutiny standards to entities based on demographic assumptions</li>
            </ul>

            <h3 className="text-sm font-semibold text-slate-200">3.3 Data Exfiltration</h3>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Copying investigative data to personal devices, personal email accounts, or unapproved storage media</li>
              <li>Sharing System screenshots, exports, or analytical outputs on social media, messaging platforms, or any non-secure channel</li>
              <li>Emailing unencrypted case data to recipients outside the authorized departmental domain</li>
              <li>Photographing or screen-recording the System's interface showing active case data</li>
            </ul>

            <h3 className="text-sm font-semibold text-slate-200">3.4 System Integrity</h3>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Attempting to bypass authentication, role-based access controls, or warrant validation checks</li>
              <li>Modifying, deleting, or falsifying audit trail entries</li>
              <li>Introducing malicious software, scripts, or unauthorized browser extensions that interact with the System</li>
              <li>Performing unauthorized penetration testing, vulnerability scanning, or load testing against the System</li>
              <li>Connecting the System's network to unauthorized external networks or Internet access points</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">4. Credential Management</h2>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Credentials are issued per individual and must not be shared, lent, or delegated</li>
              <li>Passwords must meet the department's complexity requirements (minimum 12 characters, mixed case, numeric, and special characters)</li>
              <li>Users must lock or sign out of the System when stepping away from their workstation, even briefly</li>
              <li>Suspected credential compromise must be reported to the system administrator immediately — the user is responsible for all actions taken under their credentials until the compromise is reported</li>
              <li>Google Workspace SSO sessions are bound to the user's government email domain; use of personal Google accounts is not permitted</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">5. Entity Resolution Responsibilities</h2>
            <p>
              When reviewing entities in the 70–90% confidence resolution queue, investigators must:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Review all available evidence before making a merge/split decision — do not rely solely on the similarity score</li>
              <li>Document the reasoning for each decision (the System provides a notes field for this purpose)</li>
              <li>Err on the side of "Keep Separate" when uncertain — incorrectly merging two distinct individuals is a more serious error than failing to link two records of the same individual</li>
              <li>Flag any suspected systematic errors (e.g., common names producing false positives) to the system administrator for threshold adjustment</li>
              <li>Never merge entities based on assumptions about demographic similarity not evidenced in the data</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">6. Export and Downstream Use</h2>
            <p>
              Judicial dossiers and evidence exports generated by the System may be used in:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Charge sheets and supplementary charge sheets filed under BNSS</li>
              <li>Court filings and pre-trial submissions where the investigating officer is required to present evidence</li>
              <li>Internal departmental reports and case reviews, subject to the need-to-know principle</li>
              <li>Inter-agency intelligence sharing, only where authorized by the competent judicial or administrative authority and with full audit trail documentation</li>
            </ul>
            <p className="text-slate-400">
              Exports must not be used as the sole basis for arrest, detention, search, or seizure. All 
              System outputs are investigative leads requiring independent corroboration.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">7. Reporting Obligations</h2>
            <p>Users are required to report the following to the system administrator without delay:</p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Any suspected unauthorized access to the System</li>
              <li>Any data breach or unintended disclosure of investigative data</li>
              <li>Any defect, error, or unexpected behavior in the System's analytical outputs</li>
              <li>Any attempt by a third party to obtain System access credentials or investigative data</li>
              <li>Any instruction from a superior that would require violation of this AUP</li>
            </ul>
            <p className="text-slate-400">
              Whistleblower protections under applicable law apply to good-faith reports of AUP violations 
              by other System users.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-slate-100">8. Enforcement</h2>
            <p>
              Violations of this AUP are handled through a graduated enforcement framework:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li><strong className="text-slate-300">Minor violations</strong> (e.g., failure to lock workstation): verbal warning and mandatory refresher training</li>
              <li><strong className="text-slate-300">Moderate violations</strong> (e.g., unauthorized query, credential negligence): written warning, temporary access suspension, and mandatory retraining</li>
              <li><strong className="text-slate-300">Serious violations</strong> (e.g., data exfiltration, discriminatory profiling, warrant fraud): immediate access revocation, departmental disciplinary proceedings, and referral for criminal prosecution under applicable laws</li>
            </ul>
            <p className="text-slate-400">
              All enforcement actions are recorded in the System's audit trail and in the user's departmental 
              service record.
            </p>
          </section>

        </article>
      </main>

      <footer className="border-t border-slate-800/80 bg-[#0b0f19] px-6 py-4 mt-12">
        <div className="max-w-4xl mx-auto flex items-center justify-between text-[11px] text-slate-500 font-mono">
          <span>NEXUS-CRIME · Acceptable Use Policy</span>
          <div className="flex gap-4">
            <button onClick={(e) => handleNav('/privacy', e)} className="hover:text-slate-300 transition-colors">Privacy</button>
            <button onClick={(e) => handleNav('/terms', e)} className="hover:text-slate-300 transition-colors">Terms</button>
            <button onClick={(e) => handleNav('/data-processing', e)} className="hover:text-slate-300 transition-colors">DPA</button>
          </div>
        </div>
      </footer>
    </div>
  );
}
